version: '3'

services:
  llmproxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - PORT=8080
      - CACHE_ENABLED=true
      - CACHE_TTL=300
    volumes:
      - ./ui:/app/ui
